package com.example.network;

import com.example.autogenerated.ObpfNativeInterface;

import java.util.HashMap;
import java.util.Map;

public enum Actions {
    ROTATE_CW(ObpfNativeInterface.OBPF_ACTION_ROTATE_CW()),
    ROTATE_CCW(ObpfNativeInterface.OBPF_ACTION_ROTATE_CCW()),
    HARD_DROP(ObpfNativeInterface.OBPF_ACTION_HARD_DROP()),
    TOUCH(ObpfNativeInterface.OBPF_ACTION_TOUCH()),
    CLEAR1(ObpfNativeInterface.OBPF_ACTION_CLEAR1()),
    CLEAR2(ObpfNativeInterface.OBPF_ACTION_CLEAR2()),
    CLEAR3(ObpfNativeInterface.OBPF_ACTION_CLEAR3()),
    CLEAR4(ObpfNativeInterface.OBPF_ACTION_CLEAR4()),
    ALL_CLEAR(ObpfNativeInterface.OBPF_ACTION_ALL_CLEAR());

    private static final Map<Integer, Actions> map = new HashMap<>();

    static {
        for (var type : Actions.values()) {
            map.put(type.id, type);
        }
    }

    private final int id;

    Actions(int id) {
        this.id = id;
    }

    public static Actions fromId(int id) {
        return map.get(id);
    }
}
